-- Create profiles table (safe)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  nickname text,
  avatar_url text,
  preferred_language text,
  favorite_team_ids bigint[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (safe)
alter table public.profiles enable row level security;

-- Policies for profiles - Drop first to ensure update (Idempotent)
drop policy if exists "Users can view their own profile" on profiles;
create policy "Users can view their own profile" on profiles 
  for select using (auth.uid() = id);

drop policy if exists "Users can update their own profile" on profiles;
create policy "Users can update their own profile" on profiles 
  for update using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on profiles;
create policy "Users can insert their own profile" on profiles 
  for insert with check (auth.uid() = id);

drop policy if exists "Users can delete their own profile" on profiles;
create policy "Users can delete their own profile" on profiles 
  for delete using (auth.uid() = id);

-- Create notification_tokens table
create table if not exists public.notification_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  token jsonb not null, -- Stores the PushSubscription object
  platform text check (platform in ('web', 'ios', 'android')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, token)
);

-- Enable RLS
alter table public.notification_tokens enable row level security;

-- Policies for notification_tokens
drop policy if exists "Users can view their own tokens" on notification_tokens;
create policy "Users can view their own tokens" on notification_tokens 
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own tokens" on notification_tokens;
create policy "Users can insert their own tokens" on notification_tokens 
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own tokens" on notification_tokens;
create policy "Users can delete their own tokens" on notification_tokens 
  for delete using (auth.uid() = user_id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, nickname, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Migration: Add favorite_team_ids if not exists
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'favorite_team_ids') then
    alter table public.profiles add column favorite_team_ids bigint[] default '{}'::bigint[];
  end if;
end $$;

-- Optional: Drop old column
do $$
begin
  if exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'favorite_team_id') then
    alter table public.profiles drop column favorite_team_id;
  end if;
end $$;
