-- Create profiles table
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  nickname text,
  avatar_url text,
  preferred_language text,
  favorite_team_id bigint references public.alih_teams(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Users can view their own profile" on profiles 
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on profiles 
  for update using (auth.uid() = id);

create policy "Users can insert their own profile" on profiles 
  for insert with check (auth.uid() = id);

-- Create notification_tokens table
create table if not exists public.notification_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  token jsonb not null, -- Stores the PushSubscription object
  platform text check (platform in ('web', 'ios', 'android')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, token)
);

-- Enable RLS on notification_tokens
alter table public.notification_tokens enable row level security;

-- Policies for notification_tokens
create policy "Users can view their own tokens" on notification_tokens 
  for select using (auth.uid() = user_id);

create policy "Users can insert their own tokens" on notification_tokens 
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own tokens" on notification_tokens 
  for delete using (auth.uid() = user_id);
