-- Expand-only: private administrator authority and Push delivery ledger.

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC;

CREATE TABLE IF NOT EXISTS private.alih_admin_users (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE private.alih_admin_users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE private.alih_admin_users FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.is_current_user_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM private.alih_admin_users AS admin_user
    WHERE admin_user.user_id = auth.uid()
  );
$$;

REVOKE ALL ON FUNCTION public.is_current_user_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_current_user_admin() TO authenticated;

CREATE OR REPLACE FUNCTION public.is_admin_user(p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM private.alih_admin_users AS admin_user
    WHERE admin_user.user_id = p_user_id
  );
$$;

REVOKE ALL ON FUNCTION public.is_admin_user(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin_user(UUID) TO service_role;

CREATE OR REPLACE VIEW public.public_profiles
WITH (security_barrier = true)
AS
SELECT id, nickname, avatar_url
FROM public.profiles;

REVOKE ALL ON public.public_profiles FROM PUBLIC;
GRANT SELECT ON public.public_profiles TO anon, authenticated;

CREATE TABLE IF NOT EXISTS private.alih_notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL,
  schedule_id BIGINT REFERENCES public.alih_schedule(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sending', 'sent', 'failed')),
  claimed_at TIMESTAMPTZ,
  lease_expires_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS private.alih_notification_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES private.alih_notification_events(id) ON DELETE CASCADE,
  token_id BIGINT REFERENCES public.notification_tokens(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sending', 'sent', 'failed')),
  claimed_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  lease_expires_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (event_id, token_id)
);

ALTER TABLE private.alih_notification_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.alih_notification_deliveries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE private.alih_notification_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.alih_notification_deliveries FROM PUBLIC, anon, authenticated;

CREATE INDEX IF NOT EXISTS idx_alih_notification_events_schedule
  ON private.alih_notification_events (schedule_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alih_notification_deliveries_status
  ON private.alih_notification_deliveries (status, lease_expires_at);

CREATE OR REPLACE FUNCTION public.claim_notification_event(
  p_event_key TEXT,
  p_event_type TEXT,
  p_schedule_id BIGINT,
  p_allow_retry BOOLEAN DEFAULT false
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  event_id BIGINT;
BEGIN
  INSERT INTO private.alih_notification_events (event_key, event_type, schedule_id, status, claimed_at, lease_expires_at, last_error)
  VALUES (p_event_key, p_event_type, p_schedule_id, 'sending', now(), now() + interval '10 minutes', NULL)
  ON CONFLICT (event_key) DO UPDATE
  SET status = 'sending', claimed_at = now(), lease_expires_at = now() + interval '10 minutes', last_error = NULL
  WHERE p_allow_retry
    AND (private.alih_notification_events.status = 'failed'
      OR (private.alih_notification_events.status = 'sending' AND private.alih_notification_events.lease_expires_at < now()))
  RETURNING id INTO event_id;
  RETURN event_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_notification_delivery(
  p_event_id BIGINT,
  p_token_id BIGINT,
  p_allow_retry BOOLEAN DEFAULT false
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO private.alih_notification_deliveries (event_id, token_id, status, claimed_at, lease_expires_at)
  VALUES (p_event_id, p_token_id, 'sending', now(), now() + interval '10 minutes')
  ON CONFLICT (event_id, token_id) DO UPDATE
  SET status = 'sending', claimed_at = now(), lease_expires_at = now() + interval '10 minutes', last_error = NULL
  WHERE p_allow_retry
    AND (private.alih_notification_deliveries.status = 'failed'
      OR (private.alih_notification_deliveries.status = 'sending' AND private.alih_notification_deliveries.lease_expires_at < now()));
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_notification_event(
  p_event_id BIGINT,
  p_success_count INTEGER,
  p_failure_count INTEGER
)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  UPDATE private.alih_notification_events
  SET status = CASE WHEN p_failure_count > 0 THEN 'failed' ELSE 'sent' END,
      sent_at = CASE WHEN p_failure_count = 0 THEN now() ELSE NULL END,
      lease_expires_at = CASE WHEN p_failure_count = 0 THEN NULL ELSE now() + interval '5 minutes' END,
      last_error = CASE WHEN p_failure_count > 0 THEN 'One or more deliveries failed' ELSE NULL END
  WHERE id = p_event_id;
$$;

CREATE OR REPLACE FUNCTION public.complete_notification_delivery(
  p_event_id BIGINT,
  p_token_id BIGINT,
  p_success BOOLEAN,
  p_error TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  UPDATE private.alih_notification_deliveries
  SET status = CASE WHEN p_success THEN 'sent' ELSE 'failed' END,
      sent_at = CASE WHEN p_success THEN now() ELSE NULL END,
      last_error = p_error,
      lease_expires_at = CASE WHEN p_success THEN NULL ELSE now() + interval '5 minutes' END
  WHERE event_id = p_event_id AND token_id = p_token_id;
$$;

REVOKE ALL ON FUNCTION public.claim_notification_event(TEXT, TEXT, BIGINT, BOOLEAN) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.claim_notification_delivery(BIGINT, BIGINT, BOOLEAN) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_notification_delivery(BIGINT, BIGINT, BOOLEAN, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_notification_event(BIGINT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_notification_event(TEXT, TEXT, BIGINT, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_notification_delivery(BIGINT, BIGINT, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_notification_delivery(BIGINT, BIGINT, BOOLEAN, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_notification_event(BIGINT, INTEGER, INTEGER) TO service_role;

-- Administrator bootstrap is intentionally a separate one-time, user-approved operation.
-- Public profile/video/storage policies and legacy functions stay unchanged until contract migrations.
