-- ARCHIVED DRAFT: do not apply. It lacks recipient delivery tracking.
-- Use 202609100005_admin_notification_expand.sql instead.
-- V18: Durable idempotency claims for Push notifications.

CREATE TABLE IF NOT EXISTS public.alih_notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL,
  schedule_id BIGINT REFERENCES public.alih_schedule(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ,
  success_count INTEGER NOT NULL DEFAULT 0,
  failure_count INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE public.alih_notification_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.alih_notification_events FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS idx_alih_notification_events_schedule
  ON public.alih_notification_events (schedule_id, created_at DESC);
