-- =====================================================
-- V1: 기본 스키마 (profiles, notification_tokens, alih_cheers)
-- 실행일: 2026-01-04
-- 설명: 사용자 프로필, 푸시 알림 토큰, 응원 배틀 테이블
-- =====================================================

-- ===================
-- 1. profiles 테이블
-- ===================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  email TEXT,
  nickname TEXT,
  avatar_url TEXT,
  preferred_language TEXT,
  favorite_team_ids BIGINT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS 활성화
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 정책
DROP POLICY IF EXISTS "Users can view their own profile" ON profiles;
CREATE POLICY "Users can view their own profile" ON profiles 
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
CREATE POLICY "Users can update their own profile" ON profiles 
  FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
CREATE POLICY "Users can insert their own profile" ON profiles 
  FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can delete their own profile" ON profiles;
CREATE POLICY "Users can delete their own profile" ON profiles 
  FOR DELETE USING (auth.uid() = id);

-- 신규 유저 자동 프로필 생성 트리거
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, nickname, avatar_url)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ============================
-- 2. notification_tokens 테이블
-- ============================
CREATE TABLE IF NOT EXISTS public.notification_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  token JSONB NOT NULL, -- PushSubscription 객체 저장
  platform TEXT CHECK (platform IN ('web', 'ios', 'android')),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, token)
);

ALTER TABLE public.notification_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own tokens" ON notification_tokens;
CREATE POLICY "Users can view their own tokens" ON notification_tokens 
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own tokens" ON notification_tokens;
CREATE POLICY "Users can insert their own tokens" ON notification_tokens 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own tokens" ON notification_tokens;
CREATE POLICY "Users can delete their own tokens" ON notification_tokens 
  FOR DELETE USING (auth.uid() = user_id);


-- =====================
-- 3. alih_cheers 테이블 (응원 배틀)
-- =====================
CREATE TABLE IF NOT EXISTS alih_cheers (
  id BIGSERIAL PRIMARY KEY,
  game_no INTEGER NOT NULL,
  home_cheers BIGINT DEFAULT 0,
  away_cheers BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(game_no)
);

ALTER TABLE alih_cheers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read" ON alih_cheers
  FOR SELECT USING (true);

CREATE POLICY "Allow anonymous insert" ON alih_cheers
  FOR INSERT WITH CHECK (true);

-- 응원 카운트 증가 RPC
CREATE OR REPLACE FUNCTION increment_cheers(
  p_game_no INTEGER,
  p_team TEXT,  -- 'home' 또는 'away'
  p_count INTEGER DEFAULT 1
)
RETURNS TABLE(home_cheers BIGINT, away_cheers BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO alih_cheers (game_no, home_cheers, away_cheers)
  VALUES (
    p_game_no,
    CASE WHEN p_team = 'home' THEN p_count ELSE 0 END,
    CASE WHEN p_team = 'away' THEN p_count ELSE 0 END
  )
  ON CONFLICT (game_no) DO UPDATE SET
    home_cheers = alih_cheers.home_cheers + CASE WHEN p_team = 'home' THEN p_count ELSE 0 END,
    away_cheers = alih_cheers.away_cheers + CASE WHEN p_team = 'away' THEN p_count ELSE 0 END,
    updated_at = NOW();

  RETURN QUERY
  SELECT c.home_cheers, c.away_cheers
  FROM alih_cheers c
  WHERE c.game_no = p_game_no;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_cheers_game_no ON alih_cheers(game_no);

-- ⚠️ Realtime: Dashboard > Database > Replication > alih_cheers 활성화 필요
